[package]
name = "Bevy_and_Egui"
version = "0.3.0"
authors = ["pyweeker <pyweeker@gmail.com>"]
edition = "2021"
resolver = "2"



[dependencies]
bevy = "0.6"
bevy_egui = "0.10"
rand = { version = "0.7.3" }





